export function exportPatientPDF(patient: any) {
  const fmt = (d: string) => d ? new Date(d).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" }) : "—";
  const age = (dob: string) => {
    if (!dob) return "—";
    return Math.floor((Date.now() - new Date(dob).getTime()) / (1000 * 60 * 60 * 24 * 365.25)) + " yrs";
  };
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>Patient - ${patient.full_name}</title><style>body{font-family:Arial,sans-serif;padding:32px;color:#1e293b;font-size:13px}.header{display:flex;align-items:center;gap:12px;border-bottom:2px solid #0F4C3A;padding-bottom:16px;margin-bottom:24px}.logo{background:#0F4C3A;color:white;font-weight:bold;padding:8px 12px;border-radius:8px;font-size:16px}.title{font-size:20px;font-weight:bold;color:#0F4C3A}.subtitle{color:#64748b;font-size:12px}.badge{display:inline-block;padding:2px 10px;border-radius:20px;font-size:11px;font-weight:bold;background:${patient.status==="Active"?"#d1fae5":"#f1f5f9"};color:${patient.status==="Active"?"#065f46":"#475569"}}h2{font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:#94a3b8;margin:20px 0 8px}table{width:100%;border-collapse:collapse}td{padding:8px 12px;border-bottom:1px solid #f1f5f9}td:first-child{color:#94a3b8;font-size:11px;width:40%}td:last-child{font-weight:500}.diag{background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:12px;line-height:1.6}.footer{margin-top:32px;padding-top:16px;border-top:1px solid #e2e8f0;color:#94a3b8;font-size:11px;text-align:center}</style></head><body><div class="header"><div class="logo">N</div><div><div class="title">NCRS — Nutrition Care Registry System</div><div class="subtitle">Patient Summary · ${new Date().toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"})}</div></div></div><div style="display:flex;align-items:center;gap:10px;margin-bottom:8px"><h1 style="margin:0;font-size:18px">${patient.full_name}</h1><span class="badge">${patient.status}</span></div><h2>Personal Information</h2><table><tr><td>Full Name</td><td>${patient.full_name}</td></tr><tr><td>Date of Birth</td><td>${fmt(patient.date_of_birth)}</td></tr><tr><td>Age</td><td>${age(patient.date_of_birth)}</td></tr><tr><td>Sex</td><td>${patient.sex||"—"}</td></tr><tr><td>Contact</td><td>${patient.contact_number||"—"}</td></tr></table><h2>Admission Details</h2><table><tr><td>Facility</td><td>${patient.facility||"—"}</td></tr><tr><td>Ward</td><td>${patient.ward||"—"}</td></tr><tr><td>Admission Date</td><td>${fmt(patient.admission_date)}</td></tr><tr><td>Status</td><td>${patient.status}</td></tr></table><h2>Nutrition Diagnosis</h2><div class="diag">${patient.nutrition_diagnosis||"No diagnosis recorded."}</div><div class="footer">NCRS · Taimu Tech Solutions · Blantyre, Malawi</div></body></html>`;
  const win = window.open("","_blank");
  if(win){win.document.write(html);win.document.close();win.print();}
}

export function exportADIMEPDF(note: any) {
  const fmt = (d: string) => d ? new Date(d).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}) : "—";
  const sec = (label: string, content: string) => `<h2>${label}</h2><div class="content">${content||"<span style='color:#94a3b8'>Not recorded</span>"}</div>`;
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>ADIME - ${note.patient_name}</title><style>body{font-family:Arial,sans-serif;padding:32px;color:#1e293b;font-size:13px}.header{display:flex;align-items:center;gap:12px;border-bottom:2px solid #0F4C3A;padding-bottom:16px;margin-bottom:24px}.logo{background:#0F4C3A;color:white;font-weight:bold;padding:8px 12px;border-radius:8px;font-size:16px}.title{font-size:20px;font-weight:bold;color:#0F4C3A}.subtitle{color:#64748b;font-size:12px}h2{font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:#94a3b8;margin:20px 0 6px}.content{background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:12px;line-height:1.7;white-space:pre-wrap}.meta{color:#64748b;font-size:12px;margin-bottom:20px}.footer{margin-top:32px;padding-top:16px;border-top:1px solid #e2e8f0;color:#94a3b8;font-size:11px;text-align:center}</style></head><body><div class="header"><div class="logo">N</div><div><div class="title">NCRS — Nutrition Care Registry System</div><div class="subtitle">ADIME Clinical Note · ${new Date().toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"})}</div></div></div><h1 style="font-size:18px;margin-bottom:4px">${note.patient_name}</h1><div class="meta">Date: ${fmt(note.created_at)} · By: ${note.created_by||"—"}</div>${sec("A — Assessment",note.assessment)}${sec("D — Diagnosis (PES Statement)",note.diagnosis)}${sec("I — Intervention",note.intervention)}${sec("M&E — Monitoring & Evaluation",note.monitoring)}<div class="footer">NCRS · Taimu Tech Solutions · Blantyre, Malawi</div></body></html>`;
  const win = window.open("","_blank");
  if(win){win.document.write(html);win.document.close();win.print();}
}
